# Generated by Django 6.0.5 on 2026-06-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
        ('productos', '0003_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productores.productor'),
        ),
    ]
