# Generated by Django 6.0.5 on 2026-06-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_solicitud'),
    ]

    operations = []
