# Generated by Django 6.0.5 on 2026-06-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_temp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={},
        ),
    ]
