# Generated by Django 6.0.5 on 2026-06-12 05:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_solicitud_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio en Bs. (moneda local)', max_digits=10),
        ),
    ]
