# Generated by Django 6.0.5 on 2026-06-14 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_medida', models.CharField(choices=[('ARROBAS', 'arrobas'), ('LIBRAS', 'libras'), ('QUINTALES', 'quintales')], max_length=20)),
                ('precio_esperado', models.DecimalField(decimal_places=2, help_text='Precio esperado en Bs. (moneda local)', max_digits=12)),
                ('fecha_cosecha', models.DateField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'disponible'), ('RESERVADA', 'reservada'), ('VENDIDA', 'vendida')], default='DISPONIBLE', max_length=20)),
                ('fotografia', models.ImageField(upload_to='cosechas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='productos.producto')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cosecha',
                'verbose_name_plural': 'Cosechas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
