# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0003_alter_productor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='productores/'),
        ),
    ]
